
import Head from 'next/head'
import  main from '../styles/main.module.css'
import Navbar from './Navbar'
import Main from './Main'
import Footer from './Footer'

// import { Inter } from '@next/font/google'

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head> 
        <div className ={global.body}>
            <Navbar/>
             <Main/>
            <Footer/>
        </div>
      </>
      )
      }
  
       

