import Head from 'next/head'
import Hero from '@/components/Hero'
import NFTCaption from '@/components/NFTCaption'

export default function Home() {
  return (
    <>
      <Head>
        <title>Qlip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/favico.png" />
      </Head> 
      <Hero />
      <NFTCaption/>
      </>
      )
}
  
       

